language: java
sudo: required
group: edge
dist: trusty

jdk:
  - openjdk7
  - oraclejdk8

before_script: 
  - openssl s_client -CApath /etc/ssl/certs/ -connect plugins.gradle.org:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt; sudo keytool -importcert -noprompt -file /tmp/gradle.crt -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -alias root -storepass changeit;

script: 
  - cd cadc-tap-server; gradle --stacktrace clean assemble javadoc test install || break -1; cd ../
  - for db in pg oracle; do cd cadc-tap-server-$db; gradle --stacktrace clean assemble javadoc test install; cd ../; done
  - for mod in cadc-tap-schema cadc-jsqlparser-compat cadc-adql cadc-test-tap example-tap; do cd $mod; gradle --stacktrace assemble javadoc install || break -1; cd ..; done
