version: '3.2'
services:
  tap:
    image: opencadc/tap-obscore:sybase-alpine
    build: ./
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'tap_obscore'
    environment: 
      CATALINA_OPTS: "-Dtapuser.jdbc.username=$TAPUSER_JDBC_USERNAME -Dtapuser.jdbc.password=$TAPUSER_JDBC_PASSWORD -Dtapuser.jdbc.driverClassName=net.sourceforge.jtds.jdbc.Driver -Dtapuser.jdbc.url=$TAPUSER_JDBC_URL"

networks:
  tap_obscore:
