version: '3.2'
services:
  tap:
    image: opencadc/tap-obscore:pg-alpine
    build: ./
    ports:
      - '8080:8080'
      - '5555:5555'
    depends_on:
      - 'tapdb'
    networks:
      - 'tap_obscore'
    environment: 
      CATALINA_OPTS: "-Dtapuser.jdbc.username=TAP_SCHEMA -Dtapuser.jdbc.password=TAP_SCHEMA -Dtapuser.jdbc.driverClassName=org.postgresql.Driver -Dtapuser.jdbc.url=jdbc:postgresql://tapdb:5432/TAP"
  tapdb:
    image: opencadc/tap-pg:10
    networks:
      - 'tap_obscore'
    environment:
      POSTGRES_USER: TAP_SCHEMA
      POSTGRES_PASSWORD: TAP_SCHEMA
      POSTGRES_DB: TAP

networks:
  tap_obscore:
