steps:

# Build Docker Container
 - id: build container
   name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/tap-adql-bq:${BUILD_ID}', '-t', 'gcr.io/$PROJECT_ID/tap-adql-bq:v1','-t', 'gcr.io/$PROJECT_ID/tap-adql-bq:latest','.']

images:
  - gcr.io/$PROJECT_ID/tap-adql-bq:${BUILD_ID}
  - gcr.io/$PROJECT_ID/tap-adql-bq:v1
  - gcr.io/$PROJECT_ID/tap-adql-bq:latest